### ISSUE TITLE
CACC controller

### ISSUE THREAD

**Issue by gargmohit24** [michele-segata/plexe-veins#25]
Hi Michele,

I am wondering, would CACC fallbacks to ACC when information is not available from the preceding vehicle available in CACC controllers available in plexe? 

Do you have any idea how to implement this fallback in mixed traffic scenarios? Any leads would be appreciated.

Thanks.

**Comment by michele-segata** [comment]
Dear @gargmohit24,
this is not currently implemented in Plexe, but we are working on it. I can't really give you many advises because the procedure is far from trivial. We are currently researching into this and a lot of safety problems arise. We have a paper under review, but it will take quite some time before it will become public. I'll keep you posted.
