### ISSUE TITLE
Vehicle collided after lane change

### ISSUE THREAD

**Issue by CYJ-GH** [michele-segata/plexe-veins#32]
Hello, I found platoons changed their lanes without considering safety in simulation. Therefore, the vehicle collided with the vehicle which was already running on that lane when changing lanes. How can I solve the problem?
![参数2](https://user-images.githubusercontent.com/93251016/195584340-6f40e460-0e26-4195-9c0c-395c72e1902f.gif)

**Comment by CYJ-GH** [comment]
The controller of the leader is ACC, and the follower is CACC, and activated "autofeeding". I control the lane changing by using the function "enable_auto_lane_changing".

**Comment by michele-segata** [comment]
As indicated on the website, the auto lane changing feature is still experimental and this is a known bug. Auto lane change is implemented [here](https://github.com/eclipse/sumo/blob/4e026900bd802b5be8009b27d7d26d0ac2bfbec0/src/microsim/cfmodels/MSCFModel_CC.cpp#L112) in the Plexe modules of SUMO.
The way it works is as follows:
1. The leader checks whether he would either get an advantage in speed by moving left or if it should move to the right to obey the keep-right rule
2. If that is the case, it checks that the left or the right lane is safely free for all the followers
3. If so, all vehicles change lane simultaneously. Otherwise, they stay there and the leader will try at the next simulation step

For reasons unknown to me, SUMO sometimes finds out the lane is free for everyone even if it is not. The bug is not easy to solve, as it occurs only in some particular situations and it is difficult to reproduce. Even if I can reproduce it, I have a though time understanding why the lane is declared free for all the vehicles and I currently have no time or resources to investigate this.
I am leaving this for you and potentially other people that might experience the issue and might be able to help me debug the code and find out what the problem is.

**Comment by CYJ-GH** [comment]
Thanks for your reply.

**Comment by michele-segata** [comment]
With respect to this issue, I improved the lane change behavior in SUMO (see the differences [here](https://github.com/michele-segata/plexe-sumo/compare/48b570d92022...03aa6ed4fd4)). It is not yet in the official SUMO release (I've just started a [pull request](https://github.com/eclipse-sumo/sumo/pull/14395)), so if you need to use that immediately, you would need to download and compile SUMO from [my repository](https://github.com/michele-segata/plexe-sumo). In addition, you need also to upgrade Plexe to version 3.1.2 if you want to use the new API for requesting a whole-platoon lane change.
