### ISSUE TITLE
OpenCV2X together with 802.11p

### ISSUE THREAD

**Issue by Gorospe** [michele-segata/plexe-veins#35]
Hello,

I am trying to analyze the "cohabitation" within the 5.8GHz frequency band. For that, I have integrated OpenCV2X in plexe and I have created my own car that has both interfaces available. For testing purposes, I am sending Platoon beacons through both interfaces at the same time. 

![image](https://github.com/michele-segata/plexe/assets/16466906/1fa836df-9d93-40fa-924f-6779f7dd456b)

Both interfaces are working correctly (send and receive messages), but my main doubt is if each type of NIC work independently or not. In reality, 802.11p sees C-V2X as noise because it won't be able to decode the frames. 

I've just made some simple simulations, but I am guessing that the PHY layer implementations of simuLTE and veins are totally independent, no? Therefore, even if I configure them to work within the same channel, they will not affect, or do they really share a "common" channel?

Thanks in advance,

Joseba

**Comment by michele-segata** [comment]
Dear Joseba,

you are completely right in your analysis. As the channel frameworks are different (Veins channel and INET), they are basically independent. I think that if you want to do such an analysis, you would need to use the 802.11p model provided by INET rather than the one provided by Veins. Still, you would need to ensure that the instance of the module representing the channel use by the two technology is the same, plus checking that 802.11p frames contributes to interference in C-V2X (and vice-versa).
I am available for further discussion, as this is something definitely interesting.

**Comment by Gorospe** [comment]
Thanks for the answer Michele. Let me check the 802.11p model to understand how it i used and I will come back to you (maybe by email will be better) for further discussions.
