### ISSUE TITLE
Error while running Tutorial-Extending Plexe

### ISSUE THREAD

**Issue by dsg1320** [michele-segata/plexe-veins#36]
I installed Plexe 3.0 and made modifications according to whats given in the tutorial but its giving me the following error:

RUNTIME ERROR. A cRuntimeError exception is about to be thrown, and you
requested (by setting debug-on-errors=true in the ini file) that errors
abort execution and break into the debugger.
<!> Invalid controller selected -- in module (plexe::SinusoidalScenario) Highway.node[0].scenario (id=10), at t=1.01s, event #103
TRAPPING on the exception above, due to a debug-on-errors=true configuration option. Is your debugger ready?
zsh: trace trap  plexe_run -u Cmdenv -c SinusoidalNoGui -r 6
Step #0.00 (0ms ?*RT. ?UPS, TraCI: 53ms, vehicles TOT 0 ACT 0 BUF 0)            Step #1.00 (1ms ~= 10.00*RT, ~8000.00UPS, TraCI: 3ms, vehicles TOT 8 ACT 8 BUF 0plexe:~/src/plexe/examples/platooning% Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).
<!> Error launching TraCI server ("sumo --remote-port 45779 --seed 0 --configuration-file ./sumocfg/freeway.sumo.cfg"): exited with code 1. Make sure you have set $PATH correctly. -- in module (veins::TraCIScenarioManagerForker) Highway.manager (id=5), during network initialization

**Comment by michele-segata** [comment]
It's impossible to tell what is wrong because you did not detail your changes. However, the error is thrown [here](https://github.com/michele-segata/plexe/blob/81f0d05719a87e52273e02cb0c8f87b029b056d6/src/plexe/mobility/TraCIBaseTrafficManager.cc#L82). If you implemented a new controller, you should modify there to consider yours as well.

**Comment by dsg1320** [comment]
We are using instant plexe 3.0. According to the documentation of Plexe 3.0 Tutorial No.2 (Extending Plexe) given in the [Link](https://plexe.car2x.org/tutorial/example2/) we had made changes in Plexe and SUMO files in the source code inorder to incorporate a user-defined controller 'MYCC'.

After setting up the environment we ran the command :
`cd ~/src/plexe/examples/platooning`
`plexe_run -u Cmdenv -c SinusoidalNoGui -r 6`

<img width="956" alt="image" src="https://github.com/michele-segata/plexe/assets/73653978/f0d16e42-2276-4bc2-9499-9a8b8f8d78b3">
<img width="954" alt="image" src="https://github.com/michele-segata/plexe/assets/73653978/4cc832f4-0b41-4128-8443-f30d31aa2a6d">

The snippet:
`enum ACTIVE_CONTROLLER TraCIBaseTrafficManager::strToController(const char* controller)
{
    if (strcmp(controller, "ACC") == 0) {
        return ACC;
    }
    else if (strcmp(controller, "CACC") == 0) {
        return CACC;
    }
    else if (strcmp(controller, "PLOEG") == 0) {
        return PLOEG;
    }
    else if (strcmp(controller, "CONSENSUS") == 0) {
        return CONSENSUS;
    }
    else if (strcmp(controller, "FLATBED") == 0) {
        return FLATBED;
    }
    else {
        throw cRuntimeError("Invalid controller selected");
    }
}` 
given in the file TraCIBaseTrafficManager.cc you have given where the error is thrown is not found in our installed instant plexe file.

**Comment by Sid9993** [comment]
> I installed Plexe 3.0 and made modifications according to whats given in the tutorial but its giving me the following error:
> 
> RUNTIME ERROR. A cRuntimeError exception is about to be thrown, and you requested (by setting debug-on-errors=true in the ini file) that errors abort execution and break into the debugger. <!> Invalid controller selected -- in module (plexe::SinusoidalScenario) Highway.node[0].scenario (id=10), at t=1.01s, event #103 TRAPPING on the exception above, due to a debug-on-errors=true configuration option. Is your debugger ready? zsh: trace trap plexe_run -u Cmdenv -c SinusoidalNoGui -r 6 Step #0.00 (0ms ?_RT. ?UPS, TraCI: 53ms, vehicles TOT 0 ACT 0 BUF 0) Step #1.00 (1ms ~= 10.00_RT, ~8000.00UPS, TraCI: 3ms, vehicles TOT 8 ACT 8 BUF 0plexe:~/src/plexe/examples/platooning% Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown Quitting (on error). <!> Error launching TraCI server ("sumo --remote-port 45779 --seed 0 --configuration-file ./sumocfg/freeway.sumo.cfg"): exited with code 1. Make sure you have set $PATH correctly. -- in module (veins::TraCIScenarioManagerForker) Highway.manager (id=5), during network initialization

I'm also having the same issue and having the same error.

**Comment by Sid9993** [comment]
> It's impossible to tell what is wrong because you did not detail your changes. However, the error is thrown [here](https://github.com/michele-segata/plexe/blob/81f0d05719a87e52273e02cb0c8f87b029b056d6/src/plexe/mobility/TraCIBaseTrafficManager.cc#L82). If you implemented a new controller, you should modify there to consider yours as well.

In the TraCIBaseTrafficManager.cc file of Instant Plexe 3.0, the below function:
`enum ACTIVE_CONTROLLER TraCIBaseTrafficManager::strToController(const char* controller)`
is not there. So I cannot modify there in order to consider my controller.
Also, the above-stated modification of yours is not provided in the tutorial part of extending plexe on your website.

**Comment by michele-segata** [comment]
For Plexe 3.0, the code is was mentioning is in the [BaseScenario.cc](https://github.com/michele-segata/plexe/blob/eb6c34158f5631add669ad31abcb15d0c250ab6b/src/plexe/scenarios/BaseScenario.cc#L84) file. This is indicated in the online tutorial. Did you recompile the simulator after the changes?

**Comment by dsg1320** [comment]
We had made the changes to BaseScenario.cc according to the tutorial to add the new model but we havent recompiled. How can we exactly recompile the simulator?
Also is it possible to extend plexe on instant plexe 3.0 or do we have to build plexe 3.0 on Ubuntu?

**Comment by michele-segata** [comment]
Please refer to the [Building section](http://plexe.car2x.org/building/) on the website, step 2.
To extend, do you mean upgrade? If so, yes. All the software in the VM is downloaded through git, so you can just fetch the updates and recompile the software. It might be necessary to upgrade both Veins and Plexe.

**Comment by Sid9993** [comment]
> Please refer to the [Building section](http://plexe.car2x.org/building/) on the website, step 2.
> To extend, do you mean upgrade? If so, yes. All the software in the VM is downloaded through git, so you can just fetch the updates and recompile the software. It might be necessary to upgrade both Veins and Plexe.

We are actually implementing a custom mycc controller model on “Instant Plexe 3.0” in vmware on Windows by following the tutorial on example 2 “Extending Plexe” and we followed the instructions properly regarding the changes to the source code on both plexe and sumo.
But when we complete all the tutorial and run the simulation of sinusoidal and braking scenarios we are receiving the error:
https://github.com/michele-segata/plexe/issues/36#issuecomment-1937459721

We didn’t do any kind of re-compiling and all after adding the new mycc controller.
Just we modified the source files and set up environment using . ./setenv and ran the simulation.
Since u mentioned abt re-compiling we asked u how to re-compile after the modifications or whether for recompilation there are other commands or smthng
We have already added the mycc controller condition statement in https://github.com/michele-segata/plexe/blob/eb6c34158f5631add669ad31abcb15d0c250ab6b/src/plexe/scenarios/BaseScenario.cc#L84
by following the tutorial and then also it’s showing the same error.
So we wanna knw how to resolve the issue so that we can see the simulation and analyse the result using the custom mycc controller.

**Comment by michele-segata** [comment]
At the beginning of the tutorial it is stated that, as the tutorial modifies both Plexe and SUMO source files, both software need to be re-compiled. If you change the C++ source files and don't recompile the program, you are still running the old simulation. Recompile both Plexe and SUMO and the example should work fine.

**Comment by Sid9993** [comment]
> At the beginning of the tutorial it is stated that, as the tutorial modifies both Plexe and SUMO source files, both software need to be re-compiled. If you change the C++ source files and don't recompile the program, you are still running the old simulation. Recompile both Plexe and SUMO and the example should work fine.

Ooh ok gotcha!
Can u tell how should I recompile or what are the commands for compiling after modifying the source files?

**Comment by dsg1320** [comment]
Ok recompiling it solved the error. Thank you. I'm closing this issue.
