### ISSUE TITLE
Strange E2E Latency for Platoon Leader.

### ISSUE THREAD

**Issue by edmirx** [michele-segata/plexe-veins#7]
I was making some measurements regarding the end to end latencies between vehicles. In order to do this, I modified the BaseProtocol.cc file and also the PlatooningBeacon_m.cc accordingly.

I added one field in the Platoon Beacon that keeps the simulation time. In the "BaseProtocol.cc" file, I sent the simulation time by Unicast Protocol and then received it.

When receiving and plotting the results I have realized something strange. The values of latency received from the leader are almost double as big as those from front vehicle. The even more strange thing is that these results occur only when the beaconing interval is smaller than 0.5 sec (which should not make any sense since we are speaking for e2e latency).

Is there any chance that the MAC Layer treats the packets sent from leader differently?

**Comment by michele-segata** [comment]
First of all I would need to know more about the actual latency value. Saying that the latency from the leader is almost double as big as from the front vehicle can be reasonable in terms of propagation delay. If the distance between a car and its front vehicle is `x`, then the distance between a car and the `i`-th vehicle in front of it (with `i > 1`) is `i * x`, so the propagation delay from the leader must be at least twice as much. This does not hold for channel access procedures at the MAC layer, but without knowing the actual values, it is impossible for me to understand whether they are reasonable or not.

**Comment by edmirx** [comment]
Thank you very much for your response! It is much appreciated.

Here is a plot of what I meant before. The values that are around 0.3ms are the ones obtained from the front vehicles of each platoon member, except the 2nd, since it's front vehicle is the leader.

I made the calculation and this value adds up since the transmission speed is 12Mbps and the packet size 200bytes.

All values above 0.6ms are from the leader. The propagation delay is so small that it looks just like a single line(as it should be).

Please note that here are shown transmission + propagation delay.
 
![gitlab](https://user-images.githubusercontent.com/28832054/58339368-bc65a080-7e49-11e9-98f4-cd1a7f6bcbad.png)

**Comment by edmirx** [comment]
This is how the output looks like when I turn the Beaconing Interval to 0.5 sec (in the previous comment it was 0.033 sec). As you can see now the e2e delay from leader does not stand much out of those from front vehicle.
![second](https://user-images.githubusercontent.com/28832054/58340714-c046f200-7e4c-11e9-8174-2acdc2c7e547.png)

**Comment by michele-segata** [comment]
I can confirm I can reproduce this strange behavior. I'm very busy at the moment, so I don't know when I will be able to have a look into this. I'll try my best.
If you get additional information that can help me debugging, please let me know.

**Comment by michele-segata** [comment]
I did some testing and the the result is that this is simply bad luck. What happens is that the leader, in that specific simulation, generates the beacon to be sent very shortly after another vehicle. The other vehicle starts transmitting first so the leader has to postpone its transmission because the channel is busy. To verify that this is really bad luck, I set `repeat = 10` inside the `omnetpp.ini` file to get different repetitions. Then I plotted the E2E delay for front vehicle's frames. In the legend, the number indicates the E2E delay experienced by vehicle `i`, so the E2E delay is for the beacon sent by vehicle `i-1`. Here is the result:
![propagation](https://user-images.githubusercontent.com/2064511/58530089-a6573780-81dd-11e9-8190-bdb42bef2f65.png)
As you can see, in simulation run 0, the result is the same as yours. In run 1, the issue is similar, but the E2E delay is slightly smaller (the leader might have generated the beacon a little later). In run 3, you have 3 vehicles experiencing this (but not the leader). In run 6, it is the second vehicle having this problem. In all the other simulations, this does not happen.
The reason is that there is no "clock imperfection", so even if vehicles start sending beacons at a random time (say `t0`), the next beacons will be generated at precise moments (i.e., `t0 + i * BI`, where `BI` is the beacon interval and `i` is the index of the beacon).
To avoid this problem you need to fake clock drift. `BI` must not be exactly `100 ms`, but a random number (e.g., from `99.9 ms` to `100.1 ms`) different for every vehicle.
